In [10]:
import numpy as np

# Numpy Ufunctions

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])
display(np.add(a,b)) # Add Arrays
display(np.subtract(b,a)) # Subtract Arrays
display(np.multiply(a,b)) # Multiply Arrays
display(np.divide(a,b)) # Add Arrays

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.38461538, 0.42857143, 0.46666667, 0.5       ]])

In [12]:
display(np.square(a)) # Square every element in Arrays
display(np.sqrt(b)) # Square root every element in Arrays
display(np.abs(b)) # Absolute Value of elements in Arrays
display(np.ceil(a))
display(np.floor(b)) 
display(np.round(a)) # Rounds to the nearest Integer of every element in Arrays

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

array([[3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

array([[ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
display(np.isnan(b)) # return wether element is a number or not
display(np.isfinite(a))# return wether element is a infinte or not
display(np.log(a)) # Natural log of every elements in Arrays
display(np.maximum([4,8,2,9],[1,5,6,8])) # Maximum Values between Arrays 
display(np.minimum([4,8,2,9],[1,5,6,8])) # Minimum Values between Arrays

array([[False, False, False, False],
       [False, False, False, False]])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])

array([4, 8, 6, 9])

array([1, 5, 2, 8])

In [14]:
angles = [0,30,60,90,120,180]
arr = [0,0.2,0.3,0.27,0.65]
radians = np.deg2rad(angles)

display(radians)
display(np.sin(radians)) # Returns sin of every elenent in an Array
display(np.cos(radians)) # Returns cos of every elenent in an Array
display(np.tan(radians)) # Returns tan of every elenent in an Array
display(np.arcsin(arr)) # Returns inverse sin of every elenent in an Array
display(np.arccos(arr)) # Returns inverse cos of every elenent in an Array
display(np.arctan(arr)) # Returns inverse tan of every elenent in an Array

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       3.14159265])

array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 1.22464680e-16])

array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -1.00000000e+00])

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -1.22464680e-16])

array([0.        , 0.20135792, 0.30469265, 0.27339303, 0.70758444])

array([1.57079633, 1.36943841, 1.26610367, 1.2974033 , 0.86321189])

array([0.        , 0.19739556, 0.29145679, 0.26371183, 0.57637522])